spring:
  profiles:
    #active: dev
    config:
      activate:
        on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mind-fitness-dev.coparmixnipg.ap-northeast-2.rds.amazonaws.com:3306/doongji-test?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: 9K2twpaAqw

  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 500

jwt:
  header: Authorization
  secret: 42a6c52664596d4466f2a3ac71c58ff12bb5ed657a787882c38c9482792b50834cb989deb61edbec6e828a8af8c496affaee64416e344b5a79614bbf99970ba4 # HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  token-validity-in-seconds: 86400 # 24 hours
  key-name: VuYvfy2HQZ # RANDOM.ORG를 통해 생성된 10자리 난수
  authorities-key-name: PUbSJ4Ubt0 # RANDOM.ORG를 통해 생성된 10자리 난수

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    com.doongji: DEBUG
    reactor.netty.http.client: DEBUG

cloud:
  aws:
    s3:
      bucket: # todo
    credentials:
      access-key: # todo
      secret-key: # todo
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
